// Code generated by fixture-builder. DO NOT EDIT.
package example;

final class GeneratedBoundary {
    static String generated(String value) {
        return JsonBoundary.Json.decode(value);
    }
}
