#!/usr/bin/env python3
"""Stage a compiler-resolved exact-field Java state guard from reviewed targets."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import sys
import tempfile
from typing import Any


class JavaStateGuardError(ValueError):
    """Invalid exact-authority input or unavailable staged closure."""


def _inside(root: Path, candidate: Path) -> bool:
    try:
        candidate.relative_to(root)
    except ValueError:
        return False
    return True


def _resolve(root: Path, supplied: str, label: str) -> Path:
    raw = Path(supplied)
    candidate = raw if raw.is_absolute() else root / raw
    if candidate.is_symlink():
        raise JavaStateGuardError(f"{label} must not be a symbolic link: {supplied}")
    candidate = candidate.resolve()
    if not _inside(root, candidate):
        raise JavaStateGuardError(f"{label} must stay inside project root: {supplied}")
    return candidate


def _load_targets(root: Path, supplied: str) -> dict[str, Any]:
    path = _resolve(root, supplied, "targets")
    allowed = root / "reports" / "extract-enum"
    if path == allowed or not _inside(allowed, path):
        raise JavaStateGuardError("targets must stay beneath reports/extract-enum/")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise JavaStateGuardError(f"cannot read Java enum targets: {error}") from error
    authority = payload.get("accepted_authority") if isinstance(payload, dict) else None
    required = ("qualified_owner", "package_name", "field", "field_type", "source_sha256")
    if (
        payload.get("language") != "java"
        or payload.get("status") != "review_required"
        or not isinstance(authority, dict)
        or any(not isinstance(authority.get(key), str) or not authority[key] for key in required)
        or authority.get("field_type") != "java.lang.String"
        or not isinstance(payload.get("detector_finding_id"), str)
        or not isinstance(payload.get("proposed_enum"), str)
    ):
        raise JavaStateGuardError("targets do not contain one reviewed exact Java String-field authority")
    return payload


RULE_TEMPLATE = r'''#!/usr/bin/env python3
"""Reject bare String literals on one compiler-resolved Java field."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys


RULE = "no-stringly-state"
OWNER = __OWNER__
FIELD = __FIELD__
PROPOSED_ENUM = __PROPOSED_ENUM__
MINIMUM_JDK = (17, 0, 0)
SKIP_PARTS = {".git", ".gradle", ".idea", "build", "dist", "node_modules", "out", "reports", "target", "test", "tests", "fixture", "fixtures", "integrationtest", "testfixtures", "vendor"}


class RuleError(ValueError):
    pass


def _inside(root: Path, candidate: Path) -> bool:
    try:
        candidate.relative_to(root)
    except ValueError:
        return False
    return True


def _version(tool: str) -> Path:
    executable = shutil.which(tool)
    if not executable:
        raise RuleError(f"{RULE}: Java JDK is unavailable on PATH (missing {tool})")
    result = subprocess.run([executable, "-version"], capture_output=True, text=True, check=False)
    rendered = "\n".join(part for part in (result.stdout, result.stderr) if part)
    pattern = r'\bversion\s+"?(\d+)(?:\.(\d+))?(?:\.(\d+))?' if tool == "java" else r"\bjavac\s+(\d+)(?:\.(\d+))?(?:\.(\d+))?"
    match = re.search(pattern, rendered)
    if result.returncode or match is None:
        raise RuleError(f"{RULE}: cannot determine {tool} version")
    version = tuple(int(value or 0) for value in match.groups())
    if version < MINIMUM_JDK:
        raise RuleError(f"{RULE}: Java JDK >= 17 is required")
    return Path(executable)


def _sources(root: Path) -> list[Path]:
    files: list[Path] = []
    for current, directories, names in os.walk(root, followlinks=False):
        directory = Path(current)
        directories[:] = [
            name for name in directories
            if not (directory / name).is_symlink() and name.lower() not in SKIP_PARTS
        ]
        for name in sorted(names):
            path = directory / name
            if path.suffix == ".java" and not path.is_symlink():
                head = path.read_text(encoding="utf-8", errors="replace")[:2048].lower()
                if "generated by" not in head or "do not edit" not in head:
                    files.append(path)
    return sorted(files)


def _targets(root: Path, supplied: list[str]) -> set[str]:
    output: set[str] = set()
    for item in supplied:
        raw = Path(item)
        path = raw if raw.is_absolute() else root / raw
        if path.is_symlink() or not path.is_file() or path.suffix != ".java":
            raise RuleError(f"{RULE}: target must be an existing non-symlink .java file: {item}")
        path = path.resolve()
        if not _inside(root, path):
            raise RuleError(f"{RULE}: target outside project root: {item}")
        output.add(path.relative_to(root).as_posix())
    return output


def _analyze(java: Path, root: Path, sources: list[Path]) -> dict:
    helper = Path(__file__).with_name("detect_java_state.java")
    if not helper.is_file():
        raise RuleError(f"{RULE}: staged compiler helper is missing")
    command = [str(java), str(helper), "--project-root", str(root)]
    for source in sources:
        command.extend(("--file", str(source)))
    result = subprocess.run(command, cwd=root, capture_output=True, text=True, check=False)
    if result.returncode:
        raise RuleError(result.stderr.strip() or f"{RULE}: compiler helper failed")
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise RuleError(f"{RULE}: compiler helper emitted invalid JSON") from error
    if payload.get("status") != "complete" or not isinstance(payload.get("operations"), list):
        raise RuleError(f"{RULE}: compiler evidence is {payload.get('status', 'invalid')}; do not treat it as clean")
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True)
    parser.add_argument("targets", nargs="+")
    args = parser.parse_args()
    try:
        root = Path(args.project_root).resolve()
        if not root.is_dir() or root.is_symlink():
            raise RuleError(f"{RULE}: project root is not a directory")
        target_files = _targets(root, args.targets)
        java = _version("java")
        _version("javac")
        sources = _sources(root)
        if not sources:
            raise RuleError(f"{RULE}: no eligible first-party Java source")
        payload = _analyze(java, root, sources)
    except (RuleError, OSError) as error:
        print(str(error), file=sys.stderr)
        return 2
    violations = [
        item for item in payload["operations"]
        if item.get("file") in target_files
        and item.get("field_owner") == OWNER
        and item.get("field") == FIELD
    ]
    for item in violations:
        print(
            f"{item['file']}:{item['line']}:{item['column']}: {RULE}: bare String {item['operation']} "
            f"on {OWNER}.{FIELD}; use {PROPOSED_ENUM} after the reviewed migration"
        )
    return 1 if violations else 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _rule_text(data: dict[str, Any]) -> str:
    authority = data["accepted_authority"]
    return (
        RULE_TEMPLATE.replace("__OWNER__", repr(authority["qualified_owner"]))
        .replace("__FIELD__", repr(authority["field"]))
        .replace("__PROPOSED_ENUM__", repr(data["proposed_enum"]))
    )


def _fixture_text(data: dict[str, Any], *, bad: bool) -> str:
    authority = data["accepted_authority"]
    package = authority["package_name"]
    owner = authority["qualified_owner"].rsplit(".", 1)[-1]
    field = authority["field"]
    enum = data["proposed_enum"]
    if bad:
        return f'''package {package};

public final class {owner} {{
    public String {field};

    public boolean bad() {{
        {field} = "queued";
        return {field}.equals("running") || "done".equals({field}) || {field} == "queued";
    }}
}}
'''
    return f'''package {package};

enum {enum} {{
    QUEUED,
    RUNNING,
    DONE
}}

public final class {owner} {{
    public {enum} {field};

    public boolean good() {{
        return {field} == {enum}.QUEUED;
    }}
}}

final class OtherJob {{
    String {field};

    boolean outsideExactAuthority() {{
        return {field}.equals("queued");
    }}
}}
'''


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False, dir=path.parent, prefix=f".{path.name}.") as stream:
        stream.write(text)
        temporary = Path(stream.name)
    temporary.replace(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--targets", required=True)
    parser.add_argument("--project-root", required=True)
    parser.add_argument("--output-root", required=True)
    parser.add_argument("--detector-helper")
    args = parser.parse_args(argv)
    try:
        root = Path(args.project_root).resolve()
        if not root.is_dir() or root.is_symlink():
            raise JavaStateGuardError(f"project root is not a directory: {args.project_root}")
        data = _load_targets(root, args.targets)
        output = _resolve(root, args.output_root, "output root")
        allowed = root / "reports" / "prevent-regression"
        if output == allowed or not _inside(allowed, output):
            raise JavaStateGuardError("output root must stay beneath reports/prevent-regression/")
        helper = Path(args.detector_helper).resolve() if args.detector_helper else (
            Path(__file__).resolve().parents[1].parent / "find-implicit-state" / "scripts" / "detect_java_state.java"
        )
        if not helper.is_file():
            raise JavaStateGuardError(
                "Java guard generation requires the find-implicit-state closure beside prevent-regression or --detector-helper"
            )
        authority = data["accepted_authority"]
        owner = authority["qualified_owner"].rsplit(".", 1)[-1]
        rule_dir = output / "scripts" / "lint"
        fixtures = output / "tests" / "lint"
        rule = rule_dir / "no_stringly_state.py"
        _atomic_write(rule, _rule_text(data))
        rule.chmod(0o755)
        shutil.copy2(helper, rule_dir / "detect_java_state.java")
        _atomic_write(output / "authority.json", json.dumps({
            "schema_version": 1,
            "language": "java",
            "rule": "no-stringly-state",
            "detector_finding_id": data["detector_finding_id"],
            "accepted_authority": authority,
            "proposed_enum": data["proposed_enum"],
        }, indent=2, sort_keys=True) + "\n")
        _atomic_write(fixtures / "bad" / f"{owner}.java", _fixture_text(data, bad=True))
        _atomic_write(fixtures / "good" / f"{owner}.java", _fixture_text(data, bad=False))
        _atomic_write(output / "host-wiring.diff", (
            "# Staged only. A human integrator decides whether to install this exact-field command.\n"
            f"+ python3 scripts/lint/no_stringly_state.py --project-root . <owned Java files for {authority['qualified_owner']}.{authority['field']}>\n"
        ))
    except (JavaStateGuardError, OSError, KeyError, TypeError) as error:
        print(f"[generate_java_state_guard] ERROR: {error}", file=sys.stderr)
        return 2
    print(
        f"[generate_java_state_guard] staged exact authority "
        f"{authority['qualified_owner']}.{authority['field']} at {output}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
