"""Locked native evidence for the intentionally narrow Go move-path pilot."""
from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
MOVE = ROOT / ".claude" / "skills" / "move-path" / "scripts" / "move_path.py"
FIXTURE = ROOT / "tests" / "fixtures" / "move-path-go" / "host"


def _module():
    spec = importlib.util.spec_from_file_location("go_move_path_under_test", MOVE)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _host(tmp_path: Path) -> Path:
    host = tmp_path / "host"
    shutil.copytree(FIXTURE, host)
    return host


def _plan(host: Path, *, source: str = "pkg/legacy/", destination: str = "pkg/workflow/") -> Path:
    plan = host / "move.json"
    _write(
        plan,
        json.dumps(
            {
                "moves": [{"from": source, "to": destination, "mode": "directory"}],
                "reference_scope": {"include": ["**/*.md"]},
                "rewrite": {"backtick_paths": "update", "code_imports": "update-go"},
            },
            indent=2,
        )
        + "\n",
    )
    return plan


def _run(module, host: Path, plan: Path, mode: str):
    return module.run_plan(
        plan_path=plan,
        project_root=host,
        mode=mode,
        report_dir=host / "reports" / "move-path",
    )


def test_go_leaf_package_move_updates_exact_imports_and_native_boundary(tmp_path: Path) -> None:
    module = _module()
    host = _host(tmp_path)
    plan = _plan(host)
    vendor_before = (host / "vendor" / "example.com" / "keep" / "keep.go").read_bytes()
    generated = host / "generated" / "keep.go"
    _write(generated, "// Code generated by fixture. DO NOT EDIT.\npackage generated\n")
    generated_before = generated.read_bytes()

    dry = _run(module, host, plan, "dry-run")
    assert dry["go"]["status"] == "complete"
    assert {row["file_before"] for row in dry["go"]["exact_changes"]} == {
        "app/consumer.go",
        "pkg/legacy/legacy_test.go",
    }
    assert (host / "pkg" / "legacy").is_dir()

    applied = _run(module, host, plan, "apply")
    assert applied["go"]["status"] == "complete"
    assert applied["go"]["native"]["gofmt_preflight"]["passed"] is True
    assert applied["go"]["native"]["gofmt"]["passed"] is True
    assert applied["go"]["native"]["go_test"]["passed"] is True
    assert applied["go"]["native"]["exact_diff"]["passed"] is True
    assert not (host / "pkg" / "legacy").exists()
    assert (host / "pkg" / "workflow" / "legacy.go").is_file()
    assert (host / "app" / "consumer.go").read_text(encoding="utf-8").count(
        "example.com/movefixture/pkg/workflow"
    ) == 1
    assert "example.com/movefixture/pkg/workflow" in (
        host / "pkg" / "workflow" / "legacy_test.go"
    ).read_text(encoding="utf-8")
    assert (host / "pkg" / "workflow" / "legacy_test.go").read_text(encoding="utf-8").startswith(
        "package legacy_test\n"
    )
    assert "pkg/workflow" in (host / "docs" / "move.md").read_text(encoding="utf-8")
    assert (host / "vendor" / "example.com" / "keep" / "keep.go").read_bytes() == vendor_before
    assert generated.read_bytes() == generated_before

    checked = _run(module, host, plan, "check")
    assert checked["go"]["status"] == "complete"
    assert checked["go"]["native"]["gofmt"]["passed"] is True
    assert checked["go"]["native"]["go_test"]["passed"] is True

    native = subprocess.run(["go", "test", "./..."], cwd=host, text=True, capture_output=True)
    assert native.returncode == 0, native.stdout + native.stderr


def test_copied_skill_closure_runs_without_repository_helpers(tmp_path: Path) -> None:
    host = _host(tmp_path)
    plan = _plan(host)
    installed = tmp_path / "installed" / "move-path"
    outside = tmp_path / "outside"
    outside.mkdir()
    shutil.copytree(MOVE.parents[1], installed)

    result = subprocess.run(
        [
            sys.executable,
            "-I",
            "-S",
            str(installed / "scripts" / "move_path.py"),
            "--plan",
            str(plan),
            "--project-root",
            str(host),
            "--report-dir",
            str(host / "reports"),
            "--apply",
            "--json",
        ],
        cwd=outside,
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    report = json.loads(result.stdout)
    assert report["go"]["status"] == "complete"
    assert report["go"]["native"]["go_test"]["passed"] is True


@pytest.mark.parametrize(
    ("name", "path", "content", "expected_status", "expected_kind"),
    [
        (
            "generated",
            "pkg/legacy/zz_generated.go",
            "// Code generated by fixture. DO NOT EDIT.\npackage legacy\n",
            "unsupported",
            "go_generated_source",
        ),
        (
            "malformed",
            "pkg/legacy/broken.go",
            "package legacy\nfunc broken( {\n",
            "failed",
            None,
        ),
        (
            "dynamic",
            "app/dynamic.go",
            "package app\nconst old = \"example.com/movefixture/pkg/legacy\"\n",
            "partial",
            "go_dynamic_old_path",
        ),
    ],
)
def test_go_refuses_generated_malformed_and_ambiguous_inputs(
    tmp_path: Path,
    name: str,
    path: str,
    content: str,
    expected_status: str,
    expected_kind: str | None,
) -> None:
    module = _module()
    host = _host(tmp_path / name)
    plan = _plan(host)
    _write(host / path, content)
    before = (host / "pkg" / "legacy" / "legacy.go").read_bytes()

    report = _run(module, host, plan, "dry-run")
    assert report["go"]["status"] == expected_status
    if expected_kind is not None:
        assert any(item["kind"] == expected_kind for item in report["go"]["blocked"])
    assert (host / "pkg" / "legacy" / "legacy.go").read_bytes() == before


def test_go_refuses_file_move_and_missing_or_old_tools_without_writes(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    module = _module()
    host = _host(tmp_path)
    invalid = _plan(host, source="pkg/legacy/legacy.go", destination="pkg/workflow/legacy.go")
    report = _run(module, host, invalid, "dry-run")
    assert report["go"]["status"] == "unsupported"
    assert any(item["kind"] == "go_package_move_must_be_directory" for item in report["go"]["blocked"])

    vendor = _plan(host, source="vendor/example.com/keep/", destination="pkg/keep/")
    vendor_report = _run(module, host, vendor, "dry-run")
    assert vendor_report["go"]["status"] == "unsupported"
    assert any(item["kind"] == "go_vendor_path_unsupported" for item in vendor_report["go"]["blocked"])

    plan = _plan(host)
    monkeypatch.setattr(module.shutil, "which", lambda _name: None)
    missing = _run(module, host, plan, "dry-run")
    assert missing["go"]["status"] == "unsupported"
    assert any(item["kind"] == "go_tool_missing" for item in missing["go"]["blocked"])

    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    fake_go = fake_bin / "go"
    _write(
        fake_go,
        "#!/bin/sh\n"
        "if [ \"$1\" = version ]; then echo 'go version go1.21.0 test'; exit 0; fi\n"
        "if [ \"$1\" = env ] && [ \"$2\" = GOWORK ]; then exit 0; fi\n"
        "if [ \"$1\" = env ] && [ \"$2\" = GOMOD ]; then echo \"$PWD/go.mod\"; exit 0; fi\n"
        "if [ \"$1\" = mod ]; then echo '{\"Module\":{\"Path\":\"example.com/movefixture\"},\"Go\":\"1.22\"}'; exit 0; fi\n",
    )
    fake_go.chmod(0o755)
    fake_gofmt = fake_bin / "gofmt"
    _write(fake_gofmt, "#!/bin/sh\nexit 0\n")
    fake_gofmt.chmod(0o755)
    monkeypatch.setattr(module.shutil, "which", lambda name: str(fake_go if name == "go" else fake_gofmt))
    old = module.go_tooling(host, module.load_plan(plan, host)["_moves"])
    assert old["status"] == "unsupported"
    assert old["blocked"][0]["kind"] == "go_version_too_old"


def test_go_post_native_failure_rolls_back_source_and_rewrites(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    module = _module()
    host = _host(tmp_path)
    plan = _plan(host)
    consumer_before = (host / "app" / "consumer.go").read_bytes()

    monkeypatch.setattr(
        module,
        "run_go_test",
        lambda _root, _go: {"argv": ["go", "test", "./..."], "passed": False, "returncode": 1, "stdout": "", "stderr": "forced"},
    )
    with pytest.raises(SystemExit, match="rolled back"):
        _run(module, host, plan, "apply")

    assert (host / "pkg" / "legacy" / "legacy.go").is_file()
    assert not (host / "pkg" / "workflow").exists()
    assert (host / "app" / "consumer.go").read_bytes() == consumer_before
