"""Go comment-reference, failure, source-safety, and copied-closure proof."""
from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[1]
SKILL = REPO_ROOT / ".claude" / "skills" / "audit-decisions"
FIXTURE = REPO_ROOT / "tests" / "fixtures" / "audit-decisions-go-g1"


def _go_bin() -> str:
    go = shutil.which("go")
    if go is None:
        pytest.skip("Go toolchain is unavailable")
    version = subprocess.run([go, "version"], capture_output=True, text=True, check=False)
    if version.returncode != 0 or "go1." not in version.stdout:
        pytest.skip("Go toolchain version is unavailable")
    if int(version.stdout.split("go1.", 1)[1].split(".", 1)[0]) < 22:
        pytest.skip("Go 1.22+ is required")
    return go


def _go_env(tmp_path: Path, *, path: str | None = None) -> dict[str, str]:
    go = Path(_go_bin())
    return {
        **os.environ,
        "PATH": path if path is not None else f"{go.parent}{os.pathsep}{os.environ.get('PATH', '')}",
        "GOCACHE": str(tmp_path / "go-cache"),
    }


def _run(
    *args: str, cwd: Path, env: dict[str, str] | None = None
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args, cwd=cwd, env=env, capture_output=True, text=True, check=False
    )


def _fingerprints(root: Path) -> dict[str, str]:
    return {
        path.relative_to(root).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(root.rglob("*"))
        if path.is_file()
        and "reports" not in path.relative_to(root).parts
        and ".agents" not in path.relative_to(root).parts
    }


def _host(tmp_path: Path) -> tuple[Path, dict[str, str]]:
    host = tmp_path / "host"
    shutil.copytree(FIXTURE, host)
    env = _go_env(tmp_path)
    native = _run("go", "test", "./...", cwd=host, env=env)
    assert native.returncode == 0, native.stdout + native.stderr
    return host, env


def _audit(
    skill: Path,
    host: Path,
    output: Path,
    env: dict[str, str],
    *extra: str,
) -> subprocess.CompletedProcess[str]:
    return _run(
        sys.executable,
        "-I",
        "-S",
        str(skill / "scripts" / "audit.py"),
        "--project-root",
        str(host),
        "--output-dir",
        str(output),
        *extra,
        cwd=host,
        env=env,
    )


def test_go_comments_reach_final_drift_and_source_is_read_only(tmp_path: Path) -> None:
    host, env = _host(tmp_path)
    before = _fingerprints(host)
    output = host / "reports" / "audit-decisions" / "go-final"

    result = _audit(SKILL, host, output, env)

    assert result.returncode == 1, result.stdout + result.stderr
    raw = json.loads((output / "raw-drift.json").read_text(encoding="utf-8"))
    go_refs = [item for item in raw["references"] if item["language"] == "go"]
    assert raw["status"] == "complete"
    assert raw["analysis"]["go"] == {
        "status": "complete",
        "analyzer": "go-parser-comments",
        "minimum_go_version": "1.22",
    }
    assert {(item["id"], item["comment_form"], item["resolved"]) for item in go_refs} == {
        ("0001", "line", True),
        ("0002", "block", True),
        ("9999", "line", False),
    }
    assert [row["adr_id"] for row in raw["drift"] if row["symptom"] == "code-ref-orphan"] == [
        "9999"
    ]
    assert "Go comment references: 3 total" in (output / "drift.md").read_text(
        encoding="utf-8"
    )
    assert _fingerprints(host) == before


def test_go_strings_tests_generated_and_vendor_never_create_references(tmp_path: Path) -> None:
    host, env = _host(tmp_path)
    testdata = host / "src" / "testdata" / "refs.go"
    testdata.parent.mkdir(parents=True)
    testdata.write_text(
        "package testdata\n\n// decision:9007\nconst Ignored = true\n",
        encoding="utf-8",
    )
    late_generated = host / "src" / "late_marker.go"
    late_generated.write_text(
        "\n".join(
            ["/*", "package documentation", "*/"]
            + ["// leading fixture comment" for _ in range(400)]
            + [
                "// Code generated by locked fixture. DO NOT EDIT.",
                "",
                "package refs",
                "",
                "// decision:9008",
                "const IgnoredLate = true",
                "",
            ]
        ),
        encoding="utf-8",
    )
    output = host / "reports" / "audit-decisions" / "go-boundaries"

    result = _audit(SKILL, host, output, env)

    assert result.returncode == 1, result.stdout + result.stderr
    raw = json.loads((output / "raw-drift.json").read_text(encoding="utf-8"))
    assert {item["id"] for item in raw["references"]}.isdisjoint(
        {"9001", "9002", "9003", "9004", "9005", "9006", "9007", "9008"}
    )
    assert all(
        excluded not in {item["path"] for item in raw["references"]}
        for excluded in (
            "src/refs_test.go",
            "src/generated/refs.go",
            "src/late_marker.go",
            "src/testdata/refs.go",
            "vendor/example.com/dependency/refs.go",
        )
    )


def test_go_malformed_and_missing_tool_are_not_clean_audits(tmp_path: Path) -> None:
    malformed, env = _host(tmp_path / "malformed")
    (malformed / "src" / "broken.go").write_text(
        "package refs\nfunc Broken( {\n// decision:0001\n", encoding="utf-8"
    )
    malformed_output = malformed / "reports" / "audit-decisions" / "malformed"

    malformed_result = _audit(SKILL, malformed, malformed_output, env)

    assert malformed_result.returncode == 2
    assert "status=failed" in malformed_result.stderr
    assert "syntax error" in malformed_result.stderr
    assert not malformed_output.exists()

    undecodable, undecodable_env = _host(tmp_path / "undecodable")
    (undecodable / "src" / "invalid.go").write_bytes(
        b"package refs\n\n// decision:0001\nconst Invalid = \xff\n"
    )
    undecodable_output = undecodable / "reports" / "audit-decisions" / "undecodable"
    undecodable_result = _audit(SKILL, undecodable, undecodable_output, undecodable_env)

    assert undecodable_result.returncode == 2
    assert "status=failed" in undecodable_result.stderr
    assert "cannot read Go source" in undecodable_result.stderr
    assert not undecodable_output.exists()

    missing, _ = _host(tmp_path / "missing")
    missing_output = missing / "reports" / "audit-decisions" / "missing"
    missing_result = _audit(
        SKILL,
        missing,
        missing_output,
        _go_env(tmp_path / "missing-env", path=""),
    )
    assert missing_result.returncode == 2
    assert "status=unsupported" in missing_result.stderr
    assert "Go toolchain is unavailable" in missing_result.stderr
    assert not missing_output.exists()


def test_copied_go_audit_closure_runs_outside_source_checkout(tmp_path: Path) -> None:
    host, env = _host(tmp_path)
    installed = tmp_path / "installed" / "audit-decisions"
    shutil.copytree(SKILL, installed)
    output = host / "reports" / "audit-decisions" / "copied"

    result = _audit(installed, host, output, env)

    assert result.returncode == 1, result.stdout + result.stderr
    raw = json.loads((output / "raw-drift.json").read_text(encoding="utf-8"))
    assert raw["analysis"]["go"]["status"] == "complete"
    assert (installed / "scripts" / "detect_go_comments.go").is_file()
    closure = "\n".join(
        path.read_text(encoding="utf-8")
        for path in (installed / "scripts").iterdir()
        if path.is_file()
    )
    assert "scripts/_lib" not in closure
    assert str(REPO_ROOT) not in closure


def test_go_audit_contract_declares_atomic_status_semantics() -> None:
    text = (SKILL / "SKILL.md").read_text(encoding="utf-8")

    assert "Go comments v1" in text
    assert "Go 1.22" in text
    assert "go/parser" in text
    assert "complete" in text
    assert "partial" in text
    assert "unsupported" in text
    assert "failed" in text
