#!/usr/bin/env python3
"""Render a bounded Java implicit-state review from JDK compiler facts."""
from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
from typing import Any


STATE_FIELDS = {"state", "status", "phase"}
VENDOR_OWNER = re.compile(
    r"^Vendor[A-Za-z0-9]*(?:Payload|Request|Response|Event|Message|Wire)$"
)
TEST_PARTS = {"test", "tests", "fixture", "fixtures", "integrationtest", "testfixtures"}
SKIP_PARTS = {".git", ".gradle", ".idea", "build", "dist", "node_modules", "out", "reports", "target"}
BUILD_OUTPUT_PARTS = {"build", "out", "target"}
GENERATED_PARTS = {"generated", "gen"}
MINIMUM_JDK = (17, 0, 0)


class JavaStateError(ValueError):
    """Known Java-state boundary failure."""


def _inside(root: Path, candidate: Path) -> bool:
    try:
        candidate.relative_to(root)
    except ValueError:
        return False
    return True


def _resolve_inside(root: Path, supplied: str, label: str) -> Path:
    raw = Path(supplied)
    candidate = raw if raw.is_absolute() else root / raw
    if candidate.is_symlink():
        raise JavaStateError(f"{label} must not be a symbolic link: {supplied}")
    candidate = candidate.resolve()
    if not _inside(root, candidate):
        raise JavaStateError(f"{label} must stay inside project root: {supplied}")
    return candidate


def _artifact(root: Path, supplied: str, label: str) -> Path:
    path = _resolve_inside(root, supplied, label)
    allowed = root / "reports" / "implicit-state"
    if path == allowed or not _inside(allowed, path):
        raise JavaStateError(f"{label} must stay beneath reports/implicit-state/")
    return path


def _version(executable: str, tool: str) -> tuple[Path, str]:
    found = executable or shutil.which(tool)
    if not found:
        raise JavaStateError(f"Java JDK is unavailable on PATH (missing {tool})")
    path = Path(found)
    try:
        result = subprocess.run([str(path), "-version"], capture_output=True, text=True, check=False)
    except OSError as error:
        raise JavaStateError(f"cannot run {tool}: {error}") from error
    rendered = "\n".join(part for part in (result.stdout, result.stderr) if part).strip()
    pattern = r'\bversion\s+"?(\d+)(?:\.(\d+))?(?:\.(\d+))?' if tool == "java" else r"\bjavac\s+(\d+)(?:\.(\d+))?(?:\.(\d+))?"
    match = re.search(pattern, rendered)
    if result.returncode or match is None:
        raise JavaStateError(f"cannot determine {tool} version: {rendered or 'unknown error'}")
    values = tuple(int(value or 0) for value in match.groups())
    if values < MINIMUM_JDK:
        minimum = ".".join(str(value) for value in MINIMUM_JDK)
        found_version = ".".join(str(value) for value in values)
        raise JavaStateError(f"Java state detector requires JDK >= {minimum}; {tool} reports {found_version}")
    return path, next((line for line in rendered.splitlines() if match.group(1) in line), rendered)


def _relative(root: Path, path: Path) -> str:
    return path.relative_to(root).as_posix()


def _role(root: Path, path: Path) -> str:
    relative = path.relative_to(root)
    parts = {part.lower() for part in relative.parts[:-1]}
    if parts & BUILD_OUTPUT_PARTS:
        return "excluded_build_output"
    if "vendor" in parts:
        return "excluded_vendor"
    if parts & TEST_PARTS or re.search(r"(?:Test|Tests|IT)\.java$", path.name):
        return "excluded_test"
    head = path.read_text(encoding="utf-8", errors="replace")[:2048].lower()
    if parts & GENERATED_PARTS or ("generated by" in head and "do not edit" in head):
        return "excluded_generated"
    return "first_party"


def _inventory(root: Path, target: Path) -> tuple[list[dict[str, str]], list[Path], list[str]]:
    if not target.exists():
        raise JavaStateError(f"target does not exist: {target}")
    if target.is_file():
        if target.suffix != ".java":
            raise JavaStateError("target file must use the .java suffix")
        role = _role(root, target)
        return ([{"record_kind": "source_inventory", "file": _relative(root, target), "role": role}],
                [target] if role == "first_party" else [], [])
    if not target.is_dir():
        raise JavaStateError("target must be a Java source file or directory")
    records: list[dict[str, str]] = []
    selected: list[Path] = []
    unavailable: list[str] = []
    for current, directory_names, filenames in os.walk(target, followlinks=False):
        directory = Path(current)
        kept: list[str] = []
        for name in sorted(directory_names):
            candidate = directory / name
            if candidate.is_symlink():
                relative = _relative(root, candidate)
                records.append({"record_kind": "source_inventory", "file": relative, "role": "unavailable_symlink"})
                unavailable.append(relative)
            elif name.lower() not in SKIP_PARTS:
                kept.append(name)
        directory_names[:] = kept
        for name in sorted(filenames):
            path = directory / name
            if path.suffix != ".java":
                continue
            relative = _relative(root, path)
            if path.is_symlink():
                records.append({"record_kind": "source_inventory", "file": relative, "role": "unavailable_symlink"})
                unavailable.append(relative)
                continue
            role = _role(root, path)
            records.append({"record_kind": "source_inventory", "file": relative, "role": role})
            if role == "first_party":
                selected.append(path)
    return sorted(records, key=lambda row: row["file"]), sorted(selected), sorted(unavailable)


def _run_helper(java: Path, root: Path, files: list[Path]) -> dict[str, Any]:
    helper = Path(__file__).with_name("detect_java_state.java")
    command = [str(java), str(helper), "--project-root", str(root)]
    for file in files:
        command.extend(("--file", str(file)))
    try:
        result = subprocess.run(command, cwd=root, capture_output=True, text=True, check=False)
    except OSError as error:
        raise JavaStateError(f"cannot invoke JDK compiler helper: {error}") from error
    if result.returncode:
        raise JavaStateError(result.stderr.strip() or result.stdout.strip() or "JDK compiler helper failed")
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise JavaStateError("JDK compiler helper emitted invalid JSON") from error
    if not isinstance(payload, dict) or payload.get("schema_version") != 1:
        raise JavaStateError("JDK compiler helper emitted an unsupported schema")
    if payload.get("analyzer") != "jdk-compiler-tree-type-api" or not isinstance(payload.get("operations"), list):
        raise JavaStateError("JDK compiler helper omitted compiler-tree operation evidence")
    return payload


def _authority(root: Path, record: dict[str, Any]) -> dict[str, Any]:
    declaration_file = record["declaration_file"]
    source = root / declaration_file
    if not source.is_file():
        raise JavaStateError(f"compiler declaration source is unavailable: {declaration_file}")
    return {
        "language": "java",
        "kind": "direct_string_field",
        "qualified_owner": record["field_owner"],
        "package_name": record["package_name"],
        "field": record["field"],
        "field_type": record["field_type"],
        "declaration_file": declaration_file,
        "declaration_line": record["declaration_line"],
        "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
    }


def _authority_key(record: dict[str, Any]) -> tuple[str, str, str, int]:
    return (
        str(record["field_owner"]),
        str(record["field"]),
        str(record["declaration_file"]),
        int(record["declaration_line"]),
    )


def _normalize(root: Path, raw_operations: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    safe_groups: dict[tuple[str, str, str, int], list[dict[str, Any]]] = defaultdict(list)
    unsafe_groups: dict[tuple[str, str, str, int], list[dict[str, Any]]] = defaultdict(list)
    normalized: list[dict[str, Any]] = []
    for raw in raw_operations:
        required = ("file", "line", "column", "operation", "literal", "field_owner", "package_name", "field", "field_type", "declaration_file", "declaration_line")
        if not all(key in raw for key in required):
            raise JavaStateError("JDK compiler helper emitted incomplete operation evidence")
        item = {key: raw[key] for key in required}
        item["record_kind"] = "operation"
        item["evidence"] = raw.get("evidence", "")
        authority = _authority(root, raw)
        item["authority"] = authority
        key = _authority_key(raw)
        if raw.get("unsafe_reference_equality") is True:
            item["classification"] = "unsafe_string_comparison"
            item["evidence_strength"] = "correctness_finding_not_enum_evidence"
            unsafe_groups[key].append(item)
        elif str(raw["field"]).lower() not in STATE_FIELDS:
            item["classification"] = "unrelated_string_field"
            item["evidence_strength"] = "excluded"
        elif VENDOR_OWNER.fullmatch(str(raw["field_owner"]).rsplit(".", 1)[-1]):
            item["classification"] = "vendor_wire_boundary"
            item["evidence_strength"] = "boundary_candidate"
        else:
            safe_groups[key].append(item)
        normalized.append(item)
    accepted: list[dict[str, Any]] = []
    for _key, operations in sorted(safe_groups.items()):
        literals = {str(item["literal"]) for item in operations}
        if len(operations) >= 3 and len(literals) >= 2:
            for item in operations:
                item["classification"] = "first_party_state_operation"
                item["evidence_strength"] = "review_candidate"
            authority = operations[0]["authority"]
            accepted.append({
                "authority": authority,
                "operations": operations,
                "literals": sorted(literals),
            })
        else:
            for item in operations:
                item["classification"] = "insufficient_closed_state_evidence"
                item["evidence_strength"] = "insufficient"
    unsafe = [
        {"authority": operations[0]["authority"], "operations": operations}
        for _key, operations in sorted(unsafe_groups.items())
    ]
    return normalized, accepted, unsafe


def _final_findings(
    root: Path,
    scan_id: str,
    target: Path,
    inventory: list[dict[str, str]],
    source_files: list[Path],
    helper: dict[str, Any],
    unavailable: list[str],
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    normalized, accepted, unsafe = _normalize(root, helper.get("operations", []))
    helper_status = str(helper.get("status", "partial"))
    status = "complete" if helper_status == "complete" and not unavailable else "partial"
    findings: list[dict[str, Any]] = []
    for index, candidate in enumerate(accepted, 1):
        calls = candidate["operations"]
        findings.append({
            "finding_id": f"java-implicit-state-{index:04d}",
            "language": "java",
            "status": "accepted" if status == "complete" else "blocked_partial",
            "bucket": "extract_enum_candidate",
            "recommendation_hint": "extract_enum_candidate",
            "kind": "compiler_resolved_repeated_string_state",
            "authority": candidate["authority"],
            "hit_count": len(calls),
            "literal_count": len(candidate["literals"]),
            "literals": candidate["literals"],
            "callsites": [
                {key: item[key] for key in ("file", "line", "column", "operation", "literal", "evidence")}
                for item in calls
            ],
        })
    for index, candidate in enumerate(unsafe, 1):
        calls = candidate["operations"]
        findings.append({
            "finding_id": f"java-unsafe-string-comparison-{index:04d}",
            "language": "java",
            "status": "review_required",
            "bucket": "unsafe_string_comparison",
            "recommendation_hint": "repair_string_comparison",
            "kind": "unsafe_reference_string_equality",
            "authority": candidate["authority"],
            "hit_count": len(calls),
            "callsites": [
                {key: item[key] for key in ("file", "line", "column", "operation", "literal", "evidence")}
                for item in calls
            ],
            "not_enum_evidence": True,
        })
    classifications = Counter(item.get("classification", "unknown") for item in normalized)
    roles = Counter(item["role"] for item in inventory)
    payload = {
        "schema_version": 1,
        "skill": "find-implicit-state",
        "scan_id": scan_id,
        "language": "java",
        "status": status,
        "target": _relative(root, target),
        "source_manifest": {
            "algorithm": "sha256",
            "files": {
                _relative(root, path): hashlib.sha256(path.read_bytes()).hexdigest()
                for path in source_files
            },
        },
        "analysis": {
            "status": status,
            "analyzer": "jdk-compiler-tree-type-api",
            "minimum_jdk": 17,
            "java_version": helper.get("java_version"),
            "diagnostics": helper.get("diagnostics", []),
            "unavailable_files": unavailable,
            "files": dict(sorted(roles.items())),
        },
        "summary": {
            "findings_total": len(findings),
            "buckets": dict(sorted(Counter(item["bucket"] for item in findings).items())),
            "classifications": dict(sorted(classifications.items())),
        },
        "findings": findings,
        "boundaries": {
            "source_inventory": inventory,
            "operations": normalized,
        },
    }
    return payload, [{"record_kind": "analysis_status", "status": status, "analyzer": "jdk-compiler-tree-type-api", "unavailable_files": unavailable}, *inventory, *normalized]


def _render_report(payload: dict[str, Any]) -> str:
    lines = [
        f"# Implicit-state audit — Java {payload['scan_id']}",
        "",
        f"**Status:** {payload['status']}",
        f"**Target:** `{payload['target']}`",
        f"**Analyzer:** `{payload['analysis']['analyzer']}` (JDK ≥ {payload['analysis']['minimum_jdk']})",
        "",
        "## Accepted enum-review candidates",
        "",
        "| Finding | Exact field authority | Calls | Literals | Next action |",
        "|---|---|---:|---:|---|",
    ]
    candidates = [
        item for item in payload["findings"]
        if item["bucket"] == "extract_enum_candidate" and item["status"] == "accepted"
    ]
    if candidates:
        for item in candidates:
            authority = item["authority"]
            lines.append(
                f"| `{item['finding_id']}` | `{authority['qualified_owner']}.{authority['field']}` | "
                f"{item['hit_count']} | {item['literal_count']} | `/extract-enum {item['finding_id']}` |"
            )
    else:
        lines.append("| — | No complete compiler-resolved repeated state field | 0 | 0 | No enum proposal |")
    lines.extend(["", "## Unsafe String reference equality", ""])
    unsafe = [item for item in payload["findings"] if item["bucket"] == "unsafe_string_comparison"]
    if unsafe:
        lines.append("These are correctness findings, not evidence that an enum is appropriate.")
        lines.append("")
        for item in unsafe:
            authority = item["authority"]
            lines.append(f"- `{item['finding_id']}` — `{authority['qualified_owner']}.{authority['field']}` ({item['hit_count']} `==`/`!=` call(s)); repair with value equality.")
    else:
        lines.append("No unsafe `String` reference equality was found on compiler-resolved direct fields.")
    lines.extend(["", "## Explicit boundaries", ""])
    roles = payload["analysis"]["files"]
    lines.append("- Source roles: " + ", ".join(f"`{role}`={count}" for role, count in sorted(roles.items())) + ".")
    boundaries = payload["summary"]["classifications"]
    if boundaries:
        lines.append("- Operation classifications: " + ", ".join(f"`{name}`={count}" for name, count in sorted(boundaries.items())) + ".")
    unavailable = payload["analysis"]["unavailable_files"]
    if unavailable:
        lines.append("- Incomplete evidence: " + ", ".join(f"`{path}`" for path in unavailable) + "; no proposal is authorized.")
    lines.extend(["", "## Next action", ""])
    if payload["status"] != "complete":
        lines.append("Resolve incomplete compiler evidence and re-run; partial Java analysis is not a clean outcome.")
    elif candidates:
        lines.append(f"Hand exactly one accepted finding to `/extract-enum {candidates[0]['finding_id']}`. The next skill must consume this artifact and must not re-detect source.")
    else:
        lines.append("No Java enum migration is proposed from this scan.")
    return "\n".join(lines) + "\n"


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False, dir=path.parent, prefix=f".{path.name}.") as stream:
        stream.write(text)
        temporary = Path(stream.name)
    temporary.replace(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", required=True)
    parser.add_argument("--project-root", required=True)
    parser.add_argument("--output", required=True, help="JSONL evidence beneath reports/implicit-state/")
    parser.add_argument("--findings", required=True, help="final findings.json beneath reports/implicit-state/")
    parser.add_argument("--report", required=True, help="final report.md beneath reports/implicit-state/")
    parser.add_argument("--scan-id", default="java-state")
    parser.add_argument("--java-executable")
    parser.add_argument("--javac-executable")
    args = parser.parse_args(argv)
    try:
        root = Path(args.project_root).resolve()
        if not root.is_dir() or root.is_symlink():
            raise JavaStateError(f"project root is not a directory: {args.project_root}")
        target = _resolve_inside(root, args.target, "target")
        output = _artifact(root, args.output, "output")
        findings = _artifact(root, args.findings, "findings")
        report = _artifact(root, args.report, "report")
        if len({output, findings, report}) != 3:
            raise JavaStateError("output, findings, and report paths must be distinct")
        java, java_version = _version(args.java_executable, "java")
        _javac, javac_version = _version(args.javac_executable, "javac")
        inventory, files, unavailable = _inventory(root, target)
        if files:
            helper = _run_helper(java, root, files)
            if helper.get("status") == "syntax-error":
                detail = "; ".join(str(item) for item in helper.get("diagnostics", []))
                raise JavaStateError(f"Java syntax error: {detail}")
        else:
            helper = {"schema_version": 1, "analyzer": "jdk-compiler-tree-type-api", "java_version": java_version, "status": "partial", "diagnostics": ["no eligible first-party Java source"], "operations": []}
        payload, records = _final_findings(
            root, args.scan_id, target, inventory, files, helper, unavailable
        )
        payload["analysis"]["java_tool"] = java_version
        payload["analysis"]["javac_tool"] = javac_version
        _atomic_write(output, "".join(json.dumps(record, sort_keys=True) + "\n" for record in records))
        _atomic_write(findings, json.dumps(payload, indent=2, sort_keys=True) + "\n")
        _atomic_write(report, _render_report(payload))
    except (JavaStateError, OSError, json.JSONDecodeError) as error:
        print(f"[detect_java_state] ERROR: {error}", file=sys.stderr)
        return 2
    print(
        f"[detect_java_state] files={len(files)} operations={len(helper['operations'])} "
        f"findings={payload['summary']['findings_total']} status={payload['status']}",
        file=sys.stderr,
    )
    print(f"[report_implicit_state] wrote {report}", file=sys.stderr)
    print(f"[report_implicit_state] wrote {findings}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
