// Code generated by fixturegen; DO NOT EDIT.

package complexity

func markerGeneratedHotspot(value int) int {
	if value > 0 {
		value--
	}
	if value > 1 {
		value--
	}
	if value > 2 {
		value--
	}
	if value > 3 {
		value--
	}
	if value > 4 {
		value--
	}
	if value > 5 {
		value--
	}
	if value > 6 {
		value--
	}
	if value > 7 {
		value--
	}
	if value > 8 {
		value--
	}
	if value > 9 {
		value--
	}
	if value > 10 {
		value--
	}
	if value > 11 {
		value--
	}
	if value > 12 {
		value--
	}
	if value > 13 {
		value--
	}
	if value > 14 {
		value--
	}
	if value > 15 {
		value--
	}
	if value > 16 {
		value--
	}
	if value > 17 {
		value--
	}
	return value
}
