// Generated by the locked fixture. DO NOT EDIT.
package example;

public class GeneratedFormatter {
    public String summarize(java.util.List<String> values) {
        String result = "";
        for (String value : values) {
            result += value.trim();
        }
        return result;
    }
}
