#!/usr/bin/env python3
"""Generate a product workflow map.

The workflow's shape (steps, route shape, UI template/script globs) is
host-authored in `.engineering/docs/product-workflows.md`; this script ships no
baked-in profile. With no descriptor the scanners find nothing rather than
assuming another project's layout. Generic scanners cover routes, views,
templates, JavaScript boot globals, docs references, and status-provider
candidates.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "_common"))
from product_topology import (  # noqa: E402
    dataclass_dicts,
    discover_root_urlconf,
    extract_docs_routes,
    extract_python_surface,
    extract_routes,
    extract_window_accesses,
    iter_files,
    route_by_name,
    status_provider_names,
    utc_scan_id,
    write_json,
)
from product_health import expand_paths  # noqa: E402
from workflows import (  # noqa: E402
    workflow_targets,
    workflow_steps,
    workflow_ui_script_globs,
    workflow_ui_template_globs,
)


def _expand_globs(project_root: Path, patterns: list[str]) -> list[Path]:
    """Resolve repo-relative glob patterns to sorted, unique files (dirs skipped)."""
    paths: set[Path] = set()
    for pattern in patterns:
        paths.update(project_root.glob(pattern))
    return sorted(path for path in paths if path.is_file())


def _workflow_paths(project_root: Path) -> tuple[list[Path], list[Path]]:
    """The workflow's UI templates and scripts, declared host-side in
    `.engineering/docs/product-workflows.md`. Empty when no descriptor — the
    toolkit assumes no host UI layout."""
    templates = _expand_globs(project_root, workflow_ui_template_globs(project_root))
    js_paths = _expand_globs(project_root, workflow_ui_script_globs(project_root))
    return templates, js_paths


def _route_table(routes: list[object], family: str) -> list[str]:
    rows = ["| Route | Name | View | File |", "|---|---|---|---|"]
    for route in routes:
        if route.route_family != family:
            continue
        rows.append(
            f"| `{route.normalized_path}/` | `{route.name or '—'}` | "
            f"`{route.view or '—'}` | `{route.file}:{route.lineno}` |"
        )
    return rows


def render_workflow_map(project_root: Path, workflow_name: str) -> tuple[str, dict[str, object]]:
    steps = workflow_steps(project_root)
    target_patterns = workflow_targets(project_root)
    ui_template_patterns = workflow_ui_template_globs(project_root)
    ui_script_patterns = workflow_ui_script_globs(project_root)
    root_urls = discover_root_urlconf(project_root, "map-product-workflow")
    routes = extract_routes(project_root, [root_urls] if root_urls else None)
    route_names = route_by_name(routes)
    # Scan the product's declared code (the descriptor's ## Targets) for the
    # workflow's redirects, renders, and status providers — not the whole repo,
    # which would pull in unrelated apps and test fixtures.
    surface_paths = expand_paths(project_root, None, (".py",))
    redirects, renders = extract_python_surface(project_root, surface_paths)
    template_paths, js_paths = _workflow_paths(project_root)
    template_accesses = extract_window_accesses(project_root, template_paths)
    js_accesses = extract_window_accesses(project_root, js_paths)
    doc_paths = iter_files(project_root / "docs", (".md",)) + [
        path
        for path in iter_files(project_root / ".claude" / "docs", (".md",))
        if ".claude/docs/workflows" not in str(path)
    ]
    doc_mentions, redirect_claims = extract_docs_routes(project_root, doc_paths)
    providers = [
        provider
        for provider in status_provider_names(project_root, surface_paths)
        if "ai_sidecar" not in str(provider["file"])
    ]

    page_routes = [route for route in routes if route.is_site_page]
    api_routes = [route for route in routes if route.is_site_scoped_api]
    boot_assignments = [access for access in template_accesses if access.kind == "assignment"]
    js_reads = [access for access in js_accesses if access.kind == "read"]
    js_read_counts = Counter(access.name for access in js_reads)

    lines: list[str] = [
        f"# Product workflow map — {workflow_name}",
        "",
        f"Generated by `/map-product-workflow {workflow_name}`.",
        "",
        "## Descriptor Scope",
        "",
        "| Field | Count |",
        "|---|---:|",
        f"| Workflow steps | {len(steps)} |",
        f"| Target patterns | {len(target_patterns)} |",
        f"| UI template patterns | {len(ui_template_patterns)} |",
        f"| UI script patterns | {len(ui_script_patterns)} |",
        "",
        (
            "_No workflow descriptor patterns were found; this map is expected "
            "to be mostly empty until `.engineering/docs/product-workflows.md` "
            "declares the host workflow._"
            if not (steps or target_patterns or ui_template_patterns or ui_script_patterns)
            else "_Workflow scope came from `.engineering/docs/product-workflows.md`._"
        ),
        "",
        "## Workflow Steps",
        "",
        "| Step | Canonical route | Canonical path | Actual route present |",
        "|---|---|---|---|",
    ]
    for step in steps:
        route = route_names.get(step["route_name"])
        present = f"`{route.file}:{route.lineno}`" if route else "missing"
        lines.append(f"| {step['label']} | `{step['route_name']}` | `{step['path']}` | {present} |")

    lines.extend(
        [
            "",
            "## Page Routes",
            "",
            *_route_table(page_routes, "site_page"),
            "",
            "## Site-Scoped API Routes",
            "",
            *_route_table(api_routes, "site_scoped_api"),
            "",
            "## View / Template Ownership",
            "",
            "| View symbol | Template | Location |",
            "|---|---|---|",
        ]
    )
    for render in renders:
        lines.append(f"| `{render.symbol}` | `{render.template}` | `{render.file}:{render.lineno}` |")

    lines.extend(["", "## Frontend Boot Contract", "", "| Global | Assigned in template | JS read count |", "|---|---|---|"])
    for access in boot_assignments:
        lines.append(f"| `window.{access.name}` | `{access.file}:{access.lineno}` | {js_read_counts.get(access.name, 0)} |")

    lines.extend(["", "## JavaScript Modules", ""])
    for path in js_paths:
        lines.append(f"- `{path.relative_to(project_root)}`")

    lines.extend(["", "## Status Provider Candidates", ""])
    for provider in providers[:40]:
        lines.append(f"- `{provider['name']}` — `{provider['file']}:{provider['lineno']}`")
    if len(providers) > 40:
        lines.append(f"- ... {len(providers) - 40} more")

    lines.extend(["", "## Compatibility / Redirect Surface", ""])
    for redirect in redirects:
        if redirect.target_name in route_names:
            target = route_names[redirect.target_name].normalized_path + "/"
        else:
            target = redirect.target_name
        lines.append(f"- `{redirect.symbol}` redirects/reverses to `{target}` at `{redirect.file}:{redirect.lineno}`")

    lines.extend(["", "## Docs Route References", ""])
    for mention in doc_mentions[:80]:
        lines.append(f"- `{mention.route}` — `{mention.file}:{mention.lineno}`")
    if len(doc_mentions) > 80:
        lines.append(f"- ... {len(doc_mentions) - 80} more")

    lines.extend(["", "## Redirect Claims In Docs", ""])
    if redirect_claims:
        for claim in redirect_claims:
            lines.append(f"- `{claim.source}` -> `{claim.target}` — `{claim.file}:{claim.lineno}`")
    else:
        lines.append("- None found.")

    data = {
        "workflow": workflow_name,
        "descriptor_scope": {
            "workflow_steps": len(steps),
            "target_patterns": len(target_patterns),
            "ui_template_patterns": len(ui_template_patterns),
            "ui_script_patterns": len(ui_script_patterns),
        },
        "steps": list(steps),
        "page_routes": dataclass_dicts(page_routes),
        "site_scoped_api_routes": dataclass_dicts(api_routes),
        "template_renders": dataclass_dicts(renders),
        "boot_assignments": dataclass_dicts(boot_assignments),
        "js_reads": dataclass_dicts(js_reads),
        "status_providers": providers,
        "redirects": dataclass_dicts(redirects),
        "doc_route_mentions": dataclass_dicts(doc_mentions),
        "redirect_claims": dataclass_dicts(redirect_claims),
    }
    return "\n".join(lines) + "\n", data


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "workflow",
        help="Workflow name — labels the output map; the host's "
        ".engineering/docs/product-workflows.md descriptor defines its shape",
    )
    parser.add_argument("--project-root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--json-output", type=Path, default=None)
    parser.add_argument("--scan-id", default=None)
    parser.add_argument("--skip-effectiveness-log", action="store_true")
    args = parser.parse_args()

    project_root = args.project_root.resolve()
    scan_id = args.scan_id or utc_scan_id("workflow-map")
    output = args.output or project_root / ".claude" / "docs" / "workflows" / f"{args.workflow}.md"
    json_output = args.json_output or project_root / "reports" / "product-topology" / scan_id / f"{args.workflow}.json"

    markdown, data = render_workflow_map(project_root, args.workflow)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    write_json(data, json_output)

    if not args.skip_effectiveness_log:
        buckets = {
            "page_routes": len(data["page_routes"]),
            "site_scoped_api_routes": len(data["site_scoped_api_routes"]),
            "boot_assignments": len(data["boot_assignments"]),
            "doc_route_mentions": len(data["doc_route_mentions"]),
        }
        subprocess.run(
            [
                sys.executable,
                "scripts/log_effectiveness.py",
                "--skill",
                "map-product-workflow",
                "--scan-id",
                scan_id,
                "--target",
                args.workflow,
                "--findings-total",
                str(sum(buckets.values())),
                "--buckets",
                json.dumps(buckets, sort_keys=True),
            ],
            cwd=project_root,
            check=False,
        )

    print(f"wrote {output}")
    print(f"wrote {json_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
