// This deliberately precedes the canonical generated marker.
// The mapper must classify the file before putting it in the source inventory.
// Code generated by fixture tool. DO NOT EDIT.

package features

func GeneratedOnly() string {
	return "generated"
}
