// Generated by the fixture. DO NOT EDIT.
package example;

public final class GeneratedJob {
    public String status;

    public boolean generated() {
        return status.equals("generated");
    }
}
