// Code generated by fixture; DO NOT EDIT.

package implicitstate

type GeneratedJob struct {
	State string
}

func generatedState(value *GeneratedJob) bool {
	value.State = "queued"
	return value.State == "running" || value.State == "done"
}
