/*
package documentation
*/
// leading generated-file context
// Code generated by fixture-builder. DO NOT EDIT.

package duplicate

func GeneratedClone(entries []string) []string {
	result := make([]string, 0, len(entries))
	for _, entry := range entries {
		result = append(result, entry)
	}
	return result
}
