#!/usr/bin/env python3
"""Generate a portable lookup of first-party capabilities in a host project.

The shared source inventory decides which files and languages exist. This tool
adds two intentionally bounded facts: a description harvested from each
source file's own documentation, and statically resolved first-party
references where the language has an honest local resolver.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path, PurePosixPath
from typing import Any

LIBRARY_ROOT = Path(__file__).resolve().parent.parent
if str(LIBRARY_ROOT) not in sys.path:
    # Isolated execution intentionally imports only from this library root.
    sys.path.insert(0, str(LIBRARY_ROOT))

from scripts._lib.language_support.lifecycle import (  # noqa: E402
    LifecycleError,
    write_text_atomic,
)
from scripts._lib.language_support.profile import ProfileError  # noqa: E402
from scripts.source_inventory import (  # noqa: E402
    DEFAULT_PROFILES_ROOT,
    InventoryError,
    build_inventory,
)

DEFAULT_RELATIVE_OUTPUT = Path(".engineering/docs/capability-inventory.md")
DEFAULT_ROLES = ("source", "declaration")
NON_IMPORTER_ROLES = {"build", "generated", "test", "unknown", "vendor"}
REFERENCE_UNAVAILABLE = {"csharp", "swift"}
MAX_DESCRIPTION = 150
MIN_DESCRIPTION = 16

WHITESPACE_RE = re.compile(r"\s+")
BLOCK_COMMENT_RE = re.compile(r"^[ \t]*/\*\*?\s*(.*?)\s*\*/", re.DOTALL | re.MULTILINE)
MARKUP_TAG_RE = re.compile(r"<[^>]+>")
JAVADOC_INLINE_RE = re.compile(r"\{@(?:code|link|linkplain)\s+([^}]+)\}")
XML_CREF_RE = re.compile(r'<see\s+cref="(?:[A-Z]:)?([^"]+)"\s*/>')
XML_NAME_RE = re.compile(r'<(?:paramref|typeparamref)\s+name="([^"]+)"\s*/>')
JS_REFERENCE_RE = re.compile(
    r"(?:\b(?:import|export)\b(?:[^'\";]*?\bfrom\s*)?|"
    r"\brequire\s*\(|\bimport\s*\()\s*['\"]([^'\"]+)['\"]"
)
QUOTED_INCLUDE_RE = re.compile(r'^\s*#\s*include\s*"([^"]+)"', re.MULTILINE)
DART_REFERENCE_RE = re.compile(
    r"^\s*(?:import|export|part)\s+['\"]([^'\"]+)['\"]",
    re.MULTILINE,
)
RUBY_REFERENCE_RE = re.compile(
    r"^\s*require(_relative)?\s*\(?\s*['\"]([^'\"]+)['\"]",
    re.MULTILINE,
)
RUST_MOD_RE = re.compile(r"^\s*(?:pub\s+)?mod\s+([A-Za-z_][A-Za-z0-9_]*)\s*;", re.MULTILINE)
RUST_USE_RE = re.compile(
    r"^\s*use\s+(?:crate|self|super)::([A-Za-z_][A-Za-z0-9_:]*)",
    re.MULTILINE,
)
PACKAGE_RE = re.compile(r"^\s*package\s+([A-Za-z_][\w.]*)\s*;?", re.MULTILINE)
JAVA_IMPORT_RE = re.compile(r"^\s*import\s+(?:static\s+)?([\w.]+)(?:\.\*)?\s*;?", re.MULTILINE)
PHP_NAMESPACE_RE = re.compile(r"^\s*namespace\s+([\w\\]+)\s*;", re.MULTILINE)
PHP_USE_RE = re.compile(r"^\s*use\s+([\w\\]+)", re.MULTILINE)
GO_IMPORT_RE = re.compile(r'^\s*(?:[A-Za-z_][\w.]*\s+)?"([^"]+)"\s*$', re.MULTILINE)
GO_SINGLE_IMPORT_RE = re.compile(r'^\s*import\s+(?:[A-Za-z_][\w.]*\s+)?"([^"]+)"', re.MULTILINE)


class CapabilityInventoryError(ValueError):
    """Invalid, unsafe, or internally inconsistent inventory request."""


def _absolute(path: Path) -> Path:
    return Path(os.path.abspath(path))


def _is_within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def _first_paragraph(raw: str) -> str:
    lines: list[str] = []
    for line in raw.strip().splitlines():
        cleaned = line.strip().lstrip("*").strip()
        if not cleaned:
            if lines:
                break
            continue
        lines.append(cleaned)
    sentence = " ".join(lines)
    sentence = JAVADOC_INLINE_RE.sub(r"\1", sentence)
    sentence = XML_CREF_RE.sub(r"\1", sentence)
    sentence = XML_NAME_RE.sub(r"\1", sentence)
    sentence = MARKUP_TAG_RE.sub(" ", sentence)
    sentence = WHITESPACE_RE.sub(" ", sentence).strip()
    if len(sentence) <= MAX_DESCRIPTION:
        return sentence
    head = sentence[:MAX_DESCRIPTION].rsplit(" ", 1)[0]
    return f"{head or sentence[:MAX_DESCRIPTION]}…"


def _meaningful_comment(raw: str) -> str:
    sentence = _first_paragraph(raw)
    lowered = sentence.lower()
    boilerplate = (
        "copyright",
        "licensed under",
        "licensed to",
        "apache license",
        "mit license",
        "permission is hereby granted",
        "spdx-license-identifier",
        "this file is part of",
        "generated by",
        "do not edit",
        "swift-tools-version",
        "eslint-disable",
        "frozen_string_literal",
        "rubocop:",
        "!/usr/bin/env",
        "go:build",
        "coding:",
        "module dependencies",
        "external dependencies",
    )
    if len(sentence) < MIN_DESCRIPTION or any(marker in lowered for marker in boilerplate):
        return ""
    return sentence


def _line_comment_candidates(text: str, prefixes: tuple[str, ...]) -> list[tuple[int, str]]:
    candidates: list[tuple[int, str]] = []
    offset = 0
    active_offset: int | None = None
    active_prefix: str | None = None
    active_lines: list[str] = []

    def flush() -> None:
        nonlocal active_offset, active_prefix, active_lines
        if active_offset is not None and active_lines:
            candidates.append((active_offset, "\n".join(active_lines)))
        active_offset = None
        active_prefix = None
        active_lines = []

    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        prefix = next((item for item in prefixes if stripped.startswith(item)), None)
        if prefix is None:
            flush()
        else:
            if active_prefix != prefix:
                flush()
                active_offset = offset
                active_prefix = prefix
            active_lines.append(stripped[len(prefix) :].strip())
        offset += len(line)
    flush()
    return candidates


def _source_comment(source: str, language: str) -> str:
    text = source.lstrip("\ufeff")[:12000]
    candidates: list[tuple[int, str]] = []
    block_languages = {
        "c",
        "cpp",
        "csharp",
        "dart",
        "java",
        "javascript",
        "kotlin",
        "php",
        "swift",
        "typescript",
    }
    if language in block_languages:
        for match in BLOCK_COMMENT_RE.finditer(text):
            if language not in {"c", "cpp"} and not match.group(0).lstrip().startswith("/**"):
                continue
            candidates.append((match.start(), match.group(1)))

    line_prefixes = {
        "c": ("///",),
        "cpp": ("///",),
        "csharp": ("///",),
        "dart": ("///",),
        "go": ("//",),
        "ruby": ("#",),
        "rust": ("//!", "///"),
        "swift": ("///",),
    }.get(language, ())
    candidates.extend(_line_comment_candidates(text, line_prefixes))
    for _offset, raw in sorted(candidates):
        sentence = _meaningful_comment(raw)
        if sentence:
            return sentence
    return ""


def _python_description(source: str) -> tuple[str, str, str | None]:
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        return "", "unavailable", f"python syntax error at line {exc.lineno or '?'}"
    docstring = ast.get_docstring(tree, clean=True) or ""
    return _first_paragraph(docstring), "python-module-docstring", None


def _description(path: Path, language: str) -> tuple[str, str, str | None]:
    try:
        source = path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return "", "unavailable", f"source read failed: {exc}"
    if language == "python":
        return _python_description(source)
    return _source_comment(source, language), "source-documentation-comment", None


def _python_reexport_shim(path: Path, source: str) -> bool:
    if path.name != "__init__.py":
        return False
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return False
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            continue
        if isinstance(node, ast.Assign) and all(
            isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets
        ):
            continue
        return False
    return True


def _without_suffix(path: PurePosixPath) -> str:
    value = path.as_posix()
    return value[: -len(path.suffix)] if path.suffix else value


def _path_aliases(relative: str) -> set[str]:
    path = PurePosixPath(relative)
    base = _without_suffix(path)
    aliases = {base, base.replace("/", ".")}
    if path.stem in {"__init__", "index", "mod"}:
        package = path.parent.as_posix()
        aliases.update({package, package.replace("/", ".")})
    for prefix in ("src/", "lib/", "app/", "Sources/"):
        if base.startswith(prefix):
            shortened = base[len(prefix) :]
            aliases.update({shortened, shortened.replace("/", ".")})
    aliases.add(path.stem)
    return {alias.strip("./") for alias in aliases if alias.strip("./")}


def _candidate_paths(importer: str, spec: str, language: str) -> list[str]:
    importer_path = PurePosixPath(importer)
    normalized = spec.replace("\\", "/").strip("/")
    suffixes = {
        "python": (".py", ".pyi"),
        "typescript": (".ts", ".tsx", ".d.ts"),
        "javascript": (".js", ".jsx", ".mjs", ".cjs"),
        "ruby": (".rb",),
        "rust": (".rs",),
        "dart": (".dart",),
        "c": (".c", ".h"),
        "cpp": (".cpp", ".cc", ".cxx", ".hpp", ".hh", ".hxx"),
    }.get(language, ())
    bases: list[PurePosixPath] = []
    raw = PurePosixPath(normalized)
    if spec.startswith(".") or language in {"c", "cpp", "dart", "ruby", "rust"}:
        bases.append(importer_path.parent / raw)
    else:
        bases.extend(
            (
                importer_path.parent / raw,
                raw,
                PurePosixPath("src") / raw,
                PurePosixPath("lib") / raw,
            )
        )

    candidates: list[str] = []
    for base in bases:
        collapsed = PurePosixPath(os.path.normpath(base.as_posix()))
        candidates.append(collapsed.as_posix())
        if language == "typescript" and collapsed.suffix in {".js", ".jsx"}:
            stem = collapsed.as_posix()[: -len(collapsed.suffix)]
            candidates.extend((f"{stem}.ts", f"{stem}.tsx", f"{stem}.d.ts"))
        if not collapsed.suffix:
            candidates.extend(f"{collapsed.as_posix()}{suffix}" for suffix in suffixes)
            candidates.extend((collapsed / f"index{suffix}").as_posix() for suffix in suffixes)
            if language == "python":
                candidates.append((collapsed / "__init__.py").as_posix())
            if language == "rust":
                candidates.append((collapsed / "mod.rs").as_posix())
    return list(dict.fromkeys(candidates))


def _resolve_path_reference(
    importer: str,
    spec: str,
    language: str,
    known_paths: set[str],
    alias_to_paths: dict[str, set[str]],
) -> set[str]:
    for candidate in _candidate_paths(importer, spec, language):
        if candidate in known_paths:
            return {candidate}
    normalized = spec.replace("\\", "/").strip("./")
    aliases = (normalized, normalized.replace("/", "."))
    matches: set[str] = set()
    for alias in aliases:
        matches.update(alias_to_paths.get(alias, set()))
    return matches if len(matches) == 1 else set()


def _python_references(
    importer: str,
    source: str,
    known_paths: set[str],
    alias_to_paths: dict[str, set[str]],
) -> set[str]:
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return set()
    targets: set[str] = set()
    for node in ast.walk(tree):
        specs: list[str] = []
        if isinstance(node, ast.Import):
            specs.extend(alias.name.replace(".", "/") for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            prefix = "../" * max(node.level - 1, 0) if node.level else ""
            if node.level == 1:
                prefix = "./"
            base = (node.module or "").replace(".", "/")
            specs.append(f"{prefix}{base}")
            separator = "/" if base else ""
            specs.extend(f"{prefix}{base}{separator}{alias.name}" for alias in node.names)
        for spec in specs:
            targets.update(
                _resolve_path_reference(importer, spec, "python", known_paths, alias_to_paths)
            )
    return targets


def _declared_aliases(language: str, relative: str, source: str) -> set[str]:
    aliases = _path_aliases(relative)
    if language in {"java", "kotlin"}:
        package = PACKAGE_RE.search(source)
        if package:
            aliases.add(f"{package.group(1)}.{PurePosixPath(relative).stem}")
    elif language == "php":
        namespace = PHP_NAMESPACE_RE.search(source)
        if namespace:
            aliases.add(f"{namespace.group(1)}\\{PurePosixPath(relative).stem}")
    return aliases


def _go_module(project: Path) -> str | None:
    path = project / "go.mod"
    if not path.is_file():
        return None
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("module "):
            return line.removeprefix("module ").strip()
    return None


def _dart_package(project: Path) -> str | None:
    path = project / "pubspec.yaml"
    if not path.is_file():
        return None
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = re.match(r"^name:\s*([A-Za-z_][A-Za-z0-9_]*)\s*$", line)
        if match:
            return match.group(1)
    return None


def _reference_specs(language: str, source: str) -> list[tuple[str, bool]]:
    if language in {"typescript", "javascript"}:
        return [(match, False) for match in JS_REFERENCE_RE.findall(source)]
    if language in {"c", "cpp"}:
        return [(match, True) for match in QUOTED_INCLUDE_RE.findall(source)]
    if language == "dart":
        return [
            (match, match.startswith("."))
            for match in DART_REFERENCE_RE.findall(source)
            if not match.startswith("dart:")
        ]
    if language == "ruby":
        return [(spec, bool(relative)) for relative, spec in RUBY_REFERENCE_RE.findall(source)]
    if language == "rust":
        specs = [(name, True) for name in RUST_MOD_RE.findall(source)]
        specs.extend((name.replace("::", "/"), False) for name in RUST_USE_RE.findall(source))
        return specs
    if language in {"java", "kotlin"}:
        return [(match, False) for match in JAVA_IMPORT_RE.findall(source)]
    if language == "php":
        return [(match, False) for match in PHP_USE_RE.findall(source)]
    if language == "go":
        return [
            (match, False)
            for match in [*GO_SINGLE_IMPORT_RE.findall(source), *GO_IMPORT_RE.findall(source)]
        ]
    return []


def _resolve_references(
    *,
    project: Path,
    units: list[dict[str, Any]],
    importer_rows: list[dict[str, Any]],
) -> None:
    known_paths = {row["path"] for row in units}
    unit_by_path = {row["path"]: row for row in units}
    alias_to_paths: dict[str, set[str]] = defaultdict(set)
    directory_to_paths: dict[str, set[str]] = defaultdict(set)
    for row in units:
        path = project / row["path"]
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            source = ""
        for alias in _declared_aliases(row["language"], row["path"], source):
            alias_to_paths[alias].add(row["path"])
        directory_to_paths[PurePosixPath(row["path"]).parent.as_posix()].add(row["path"])

    module = _go_module(project)
    dart_package = _dart_package(project)
    inbound: dict[str, set[str]] = defaultdict(set)
    for importer in importer_rows:
        importer_path = importer["path"]
        language = importer["language"]
        if language in REFERENCE_UNAVAILABLE:
            continue
        try:
            source = (project / importer_path).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if language == "python":
            targets = _python_references(importer_path, source, known_paths, alias_to_paths)
        else:
            targets: set[str] = set()
            for spec, _relative in _reference_specs(language, source):
                if language in {"java", "kotlin", "php"}:
                    matches = alias_to_paths.get(spec, set())
                    if len(matches) == 1:
                        targets.update(matches)
                elif language == "go":
                    if module and (spec == module or spec.startswith(f"{module}/")):
                        directory = spec[len(module) :].strip("/") or "."
                        targets.update(directory_to_paths.get(directory, set()))
                elif (
                    language == "dart"
                    and dart_package
                    and spec.startswith(f"package:{dart_package}/")
                ):
                    target = f"lib/{spec.split('/', 1)[1]}"
                    if target in known_paths:
                        targets.add(target)
                else:
                    targets.update(
                        _resolve_path_reference(
                            importer_path,
                            spec,
                            language,
                            known_paths,
                            alias_to_paths,
                        )
                    )
        for target in targets:
            if target != importer_path:
                inbound[target].add(importer_path)

    for path, row in unit_by_path.items():
        if row["language"] in REFERENCE_UNAVAILABLE:
            row["used_by"] = None
            row["reference_scope"] = "unavailable"
            row["inbound_paths"] = []
            row["analysis_status"] = "partial"
            row["analysis_limitation"] = (
                f"file-level static reference attribution is unavailable for " f"{row['language']}"
            )
        else:
            paths = sorted(inbound.get(path, set()))
            row["used_by"] = len(paths)
            row["reference_scope"] = "package" if row["language"] == "go" else "file"
            row["inbound_paths"] = paths


def _collect_capability_inventory(
    project_root: Path,
    source_roots: list[Path],
    *,
    profiles_root: Path,
    languages: set[str],
    include_roles: set[str],
) -> tuple[dict[str, Any], set[Path]]:
    project = project_root.resolve()
    source_inventory = build_inventory(project, source_roots, profiles_root)
    advertised = set(source_inventory["capabilities"]["inventory_languages"])
    unknown_languages = languages - advertised
    if unknown_languages:
        raise CapabilityInventoryError(
            "unknown language filter(s): " + ", ".join(sorted(unknown_languages))
        )

    excluded_roles: Counter[str] = Counter()
    units: list[dict[str, Any]] = []
    importer_rows: list[dict[str, Any]] = []
    for source_row in source_inventory["files"]:
        if source_row["classification"] == "unsupported":
            continue
        if languages and source_row["language"] not in languages:
            continue
        if source_row["role"] not in NON_IMPORTER_ROLES:
            importer_rows.append(source_row)
        if source_row["role"] not in include_roles:
            excluded_roles[source_row["role"]] += 1
            continue

        absolute = project / source_row["path"]
        try:
            source = absolute.read_text(encoding="utf-8", errors="replace")
        except OSError:
            source = ""
        if source_row["language"] == "python" and _python_reexport_shim(absolute, source):
            continue
        description, evidence, limitation = _description(absolute, source_row["language"])
        description_status = "described" if description else "not-described"
        analysis_status = "complete"
        if evidence == "unavailable":
            description_status = "unavailable"
            analysis_status = "partial"
        row: dict[str, Any] = {
            "path": source_row["path"],
            "language": source_row["language"],
            "role": source_row["role"],
            "description": description,
            "description_status": description_status,
            "description_evidence": evidence,
            "analysis_status": analysis_status,
            "analysis_limitation": limitation,
        }
        units.append(row)

    units.sort(key=lambda row: row["path"])
    _resolve_references(project=project, units=units, importer_rows=importer_rows)
    status = "partial" if any(row["analysis_status"] == "partial" for row in units) else "complete"
    languages_present = Counter(row["language"] for row in units)
    description_counts = Counter(row["description_status"] for row in units)
    payload = {
        "schema_version": 1,
        "status": status,
        "project_root": str(project),
        "source_roots": source_inventory["source_roots"],
        "filters": {
            "languages": sorted(languages),
            "include_roles": sorted(include_roles),
        },
        "capabilities": {
            "inventory_languages": sorted(advertised),
            "description_analysis": "bounded-lexical",
            "reference_analysis": "bounded-static-local",
            "reference_unavailable_languages": sorted(REFERENCE_UNAVAILABLE),
            "runtime_usage_claimed": False,
            "mutation": "none",
        },
        "units": units,
        "counts": {
            "units": len(units),
            "languages": dict(sorted(languages_present.items())),
            "descriptions": dict(sorted(description_counts.items())),
            "excluded_roles": dict(sorted(excluded_roles.items())),
        },
    }
    source_paths = {project / row["path"] for row in source_inventory["files"]}
    return payload, source_paths


def build_capability_inventory(
    project_root: Path,
    source_roots: list[Path],
    *,
    profiles_root: Path,
    languages: set[str],
    include_roles: set[str],
) -> dict[str, Any]:
    """Build the public deterministic payload without writing host state."""
    payload, _source_paths = _collect_capability_inventory(
        project_root,
        source_roots,
        profiles_root=profiles_root,
        languages=languages,
        include_roles=include_roles,
    )
    return payload


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render_markdown(payload: dict[str, Any]) -> str:
    described = [row for row in payload["units"] if row["description_status"] == "described"]
    not_described = [
        row for row in payload["units"] if row["description_status"] == "not-described"
    ]
    unavailable = [row for row in payload["units"] if row["description_status"] == "unavailable"]
    lines = [
        "<!-- GENERATED by scripts/capability_inventory.py — do not edit by hand. -->",
        "",
        "# Capability inventory",
        "",
        "First-party source units that may already provide the capability you need.",
        "Read this before adding a new service, helper, module, or package.",
        "Descriptions come from each file's own module or source documentation.",
        "Static references are bounded evidence, not runtime usage or reachability.",
        "`—` means this tool cannot honestly attribute inbound use at file level.",
        "",
        f"{len(described)} of {len(payload['units'])} in-scope units describe themselves.",
        "",
    ]
    for language in sorted({row["language"] for row in described}):
        rows = [row for row in described if row["language"] == language]
        lines.extend(
            [
                f"## {language} — {len(rows)}",
                "",
                "| Unit | Does | Used by | Evidence |",
                "|---|---|---:|---|",
            ]
        )
        for row in rows:
            used_by = "—" if row["used_by"] is None else str(row["used_by"])
            lines.append(
                f"| `{row['path']}` | {_cell(row['description'])} | {used_by} | "
                f"{row['reference_scope']} |"
            )
        lines.append("")

    lines.extend(
        [
            f"## Not described — {len(not_described)}",
            "",
            "These units remain visible so absence of documentation cannot be mistaken",
            "for absence of a capability.",
            "",
        ]
    )
    lines.extend(f"- `{row['path']}`" for row in not_described)
    if not not_described:
        lines.append("None.")
    lines.append("")
    if unavailable:
        lines.extend([f"## Partial analysis — {len(unavailable)}", ""])
        lines.extend(f"- `{row['path']}`: {row['analysis_limitation']}" for row in unavailable)
        lines.append("")
    return "\n".join(lines)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, type=Path)
    parser.add_argument("--profiles-root", type=Path, default=DEFAULT_PROFILES_ROOT)
    parser.add_argument("--source-root", type=Path, action="append", default=[])
    parser.add_argument("--language", action="append", default=[])
    parser.add_argument("--include-role", action="append", default=[])
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--stdout", action="store_true")
    parser.add_argument(
        "--check", action="store_true", help="Exit 1 when the output is absent or stale"
    )
    parser.add_argument(
        "--no-host-write",
        action="store_true",
        help="Require stdout, check mode, or an output outside project-root",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)
    if args.stdout and args.check:
        parser.error("--stdout and --check are mutually exclusive")
    try:
        if not args.project_root.exists() or not args.project_root.is_dir():
            raise CapabilityInventoryError(
                f"project root must be an existing directory: {args.project_root}"
            )
        if args.project_root.is_symlink():
            raise CapabilityInventoryError(
                f"project root may not be a symbolic link: {args.project_root}"
            )
        project = args.project_root.resolve()
        output = _absolute(
            args.output
            or (
                project / DEFAULT_RELATIVE_OUTPUT
                if args.format == "markdown"
                else project / DEFAULT_RELATIVE_OUTPUT.with_suffix(".json")
            )
        )
        if output.is_symlink():
            raise CapabilityInventoryError(f"output may not be a symbolic link: {output}")
        if args.no_host_write and not (args.stdout or args.check) and _is_within(output, project):
            raise CapabilityInventoryError(
                "--no-host-write requires --output outside --project-root or use --stdout"
            )
        payload, source_paths = _collect_capability_inventory(
            project,
            args.source_root,
            profiles_root=args.profiles_root,
            languages=set(args.language),
            include_roles=set(args.include_role or DEFAULT_ROLES),
        )
        rendered = (
            json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n"
            if args.format == "json"
            else render_markdown(payload)
        )
        if args.stdout:
            sys.stdout.write(rendered)
            return 0
        if args.check:
            current = output.read_text(encoding="utf-8") if output.is_file() else ""
            if current != rendered:
                print(f"error: {output} is stale", file=sys.stderr)
                return 1
            print(f"{output} is current")
            return 0
        collides = output in source_paths or (
            output.exists() and any(output.samefile(path) for path in source_paths)
        )
        if collides:
            raise CapabilityInventoryError(
                f"output may not replace an inventoried source file: {output}"
            )
        write_text_atomic(output, rendered)
        print(f"Wrote {output} ({len(payload['units'])} units)")
        return 0
    except (
        CapabilityInventoryError,
        InventoryError,
        LifecycleError,
        ProfileError,
    ) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
