#!/usr/bin/env python3
"""Produce bounded C# lexical, filesystem, and Roslyn source-syntax facts."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path, PurePosixPath
from typing import Any, Iterable


SDK_VERSION = (10, 0, 302)
SDK_TEXT = "10.0.302"
TARGET_FRAMEWORK = "net10.0"
LANGUAGE_VERSION = "14.0"
TEST_DIRS = frozenset({"test", "tests", "spec", "specs", "fixtures", "testdata"})
GENERATED_DIRS = frozenset({"generated", "gen", "__generated__"})
VENDOR_DIRS = frozenset({"vendor", "vendors", "third_party", "third-party", "deps"})
BUILD_DIRS = frozenset({"build", "dist", "target", "out", ".native-build", "coverage", "bin", "obj"})
TOOLING_DIRS = frozenset({"script", "scripts", "tool", "tools"})
INTERNAL_DIRS = frozenset({
    ".git", ".hg", ".svn", ".idea", ".vs", ".native-build", ".agents", ".claude",
})
GENERATED_RE = re.compile(r"(?:<auto-generated\s*/?>|Code generated .* DO NOT EDIT\.|@generated\b)", re.I)
VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)", re.M)


def add_fact_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--dotnet")


def hash_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)


def atomic_json(path: Path, payload: Any) -> None:
    atomic_text(path, json.dumps(payload, indent=2, sort_keys=True) + "\n")


def clear_artifacts(paths: Iterable[Path]) -> None:
    for path in paths:
        if path.is_file() or path.is_symlink():
            path.unlink()


def terminal_return_code(payload: dict[str, Any], producer_code: int = 0) -> int:
    if producer_code:
        return producer_code
    return 2 if payload.get("status") == "failed" else 0


def _run(argv: list[str], cwd: Path, *, timeout: int = 120) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        argv, cwd=cwd, capture_output=True, text=True, check=False,
        shell=False, timeout=timeout,
    )


def _inside(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def _safe_relative(raw: object) -> str | None:
    if not isinstance(raw, str) or not raw or "\\" in raw:
        return None
    path = PurePosixPath(raw)
    if path.is_absolute() or ".." in path.parts or raw in {".", ""}:
        return None
    return raw


def _source_role(path: Path, root: Path, text: str) -> tuple[str, str | None]:
    parts = set(path.relative_to(root).parts[:-1])
    if parts & GENERATED_DIRS or GENERATED_RE.search(text[:4096]):
        return "generated", "excluded-generated"
    if parts & VENDOR_DIRS:
        return "vendor", "excluded-vendor"
    if parts & BUILD_DIRS:
        return "build", "excluded-build"
    if parts & TOOLING_DIRS:
        return "tooling", "excluded-tooling"
    if parts & TEST_DIRS or path.name.endswith(("Test.cs", "Tests.cs")):
        return "test", "excluded-test"
    return "source", None


def _walk_candidates(root: Path) -> list[Path]:
    found: list[Path] = []
    for current, dirs, files in os.walk(root, topdown=True, followlinks=False):
        base = Path(current)
        dirs[:] = sorted(
            name for name in dirs
            if name not in INTERNAL_DIRS and not (base / name).is_symlink()
        )
        for name in sorted(files):
            path = base / name
            if path.suffix == ".cs" and not path.is_symlink():
                found.append(path)
    return found


def _inventory(root: Path) -> tuple[list[dict[str, Any]], dict[str, str]]:
    rows: list[dict[str, Any]] = []
    manifest: dict[str, str] = {}
    for path in _walk_candidates(root):
        relative = path.relative_to(root).as_posix()
        try:
            raw = path.read_bytes()
            text = raw.decode("utf-8")
        except (OSError, UnicodeError):
            rows.append({"file": relative, "role": "unreadable", "reason": "excluded-unreadable"})
            continue
        role, reason = _source_role(path, root, text)
        digest = hash_bytes(raw)
        rows.append({
            "file": relative, "role": role, "reason": reason,
            "source_sha256": digest, "bytes": len(raw),
        })
        manifest[relative] = digest
    return rows, manifest


def _manifest_hash(rows: dict[str, str]) -> str:
    serialized = "".join(f"{path}\0{digest}\n" for path, digest in sorted(rows.items()))
    return hash_bytes(serialized.encode())


def _resolve_dotnet(requested: str | None) -> Path | None:
    raw = requested or shutil.which("dotnet")
    if not raw:
        return None
    try:
        path = Path(raw).resolve(strict=True)
    except (OSError, RuntimeError):
        return None
    return path if path.is_file() and os.access(path, os.X_OK) else None


def _probe_dotnet(root: Path, requested: str | None) -> tuple[dict[str, Any], Path | None, Path | None]:
    dotnet = _resolve_dotnet(requested)
    if dotnet is None:
        return {"status": "missing", "path": None, "version": None}, None, None
    try:
        version_result = _run([str(dotnet), "--version"], root, timeout=20)
        sdk_result = _run([str(dotnet), "--list-sdks"], root, timeout=20)
    except (OSError, subprocess.SubprocessError) as exc:
        return {"status": "unusable", "path": str(dotnet), "detail": str(exc)}, None, None
    match = VERSION_RE.search(version_result.stdout.strip())
    if version_result.returncode or not match:
        detail = (version_result.stdout + version_result.stderr).strip()[:500]
        return {"status": "unusable", "path": str(dotnet), "detail": detail}, None, None
    version = tuple(int(value) for value in match.groups())
    sdk_root: Path | None = None
    for line in sdk_result.stdout.splitlines():
        sdk_match = re.match(rf"{re.escape(SDK_TEXT)}\s+\[(.+)]$", line.strip())
        if sdk_match:
            sdk_root = Path(sdk_match.group(1)) / SDK_TEXT
            break
    status = "available" if version >= SDK_VERSION and sdk_root and sdk_root.is_dir() else "too-old"
    probe = {
        "status": status, "path": str(dotnet),
        "version": ".".join(str(value) for value in version),
        "required_sdk": SDK_TEXT,
        "sdk_root": str(sdk_root) if sdk_root else None,
    }
    return probe, dotnet if status == "available" else None, sdk_root if status == "available" else None


def _load_project(root: Path, inventory: list[dict[str, Any]]) -> dict[str, Any]:
    try:
        payload = json.loads((root / "csharp-project.json").read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ValueError("csharp-project.json is unavailable or malformed") from exc
    keys = {
        "schema_version", "target_framework", "language_version", "sources", "tests",
        "smoke_main", "smoke_output", "test_main", "test_output",
    }
    if not isinstance(payload, dict) or set(payload) != keys:
        raise ValueError("csharp-project.json has an unexpected shape")
    if (
        payload["schema_version"] != 1
        or payload["target_framework"] != TARGET_FRAMEWORK
        or payload["language_version"] != LANGUAGE_VERSION
    ):
        raise ValueError("csharp-project.json requests an unsupported contract")
    if not isinstance(payload["sources"], list) or not payload["sources"]:
        raise ValueError("csharp-project.json must declare sources")
    if not isinstance(payload["tests"], list) or not payload["tests"]:
        raise ValueError("csharp-project.json must declare tests")
    combined = [*payload["sources"], *payload["tests"]]
    if len(combined) != len(set(combined)):
        raise ValueError("csharp-project.json contains duplicate inputs")
    roles = {row["file"]: row["role"] for row in inventory}
    for role, values in (("source", payload["sources"]), ("test", payload["tests"])):
        for raw in values:
            relative = _safe_relative(raw)
            if relative is None or PurePosixPath(relative).suffix != ".cs":
                raise ValueError(f"manifest {role} must be a safe lowercase .cs path")
            path = root / relative
            if not path.is_file() or path.is_symlink() or roles.get(relative) != role:
                raise ValueError(f"manifest {role} is unavailable or has an excluded role: {relative}")
    if set(payload["sources"]) != {path for path, role in roles.items() if role == "source"}:
        raise ValueError("csharp-project.json does not exactly enumerate first-party sources")
    if set(payload["tests"]) != {path for path, role in roles.items() if role == "test"}:
        raise ValueError("csharp-project.json does not exactly enumerate tests")
    for key in ("smoke_main", "smoke_output", "test_main", "test_output"):
        if not isinstance(payload[key], str) or not payload[key]:
            raise ValueError(f"csharp-project.json must declare {key}")
    return payload


def _sdk_assets(dotnet: Path, sdk_root: Path) -> tuple[list[Path], Path, Path, str]:
    compiler = sdk_root / "Roslyn/bincore/csc.dll"
    code_analysis = sdk_root / "Roslyn/bincore/Microsoft.CodeAnalysis.dll"
    csharp_analysis = sdk_root / "Roslyn/bincore/Microsoft.CodeAnalysis.CSharp.dll"
    packs = sdk_root.parents[1] / "packs/Microsoft.NETCore.App.Ref"
    candidates = sorted(packs.glob("10.0.*/ref/net10.0"), reverse=True)
    if not compiler.is_file() or not code_analysis.is_file() or not csharp_analysis.is_file() or not candidates:
        raise ValueError("the .NET 10 compiler, Roslyn assemblies, or reference pack is unavailable")
    references = sorted(candidates[0].glob("*.dll"))
    runtime = _run([str(dotnet), "--list-runtimes"], sdk_root, timeout=20)
    versions = [
        match.group(1) for line in runtime.stdout.splitlines()
        if (match := re.match(r"Microsoft\.NETCore\.App\s+(10\.0\.\d+)\s+", line))
    ]
    if not references or not versions:
        raise ValueError("the .NET 10 reference pack or runtime is unavailable")
    return references, code_analysis, csharp_analysis, sorted(versions, reverse=True)[0]


def _runtime_config(path: Path, runtime_version: str) -> None:
    atomic_json(path, {
        "runtimeOptions": {
            "tfm": TARGET_FRAMEWORK,
            "framework": {"name": "Microsoft.NETCore.App", "version": runtime_version},
        }
    })


def _compile_command(
    dotnet: Path, compiler: Path, references: list[Path], output: Path,
    sources: list[Path], main: str, extra_references: list[Path] | None = None,
) -> list[str]:
    return [
        str(dotnet), str(compiler), "-nologo", "-noconfig", "-nostdlib+",
        f"-langversion:{LANGUAGE_VERSION}", "-nullable:enable", "-warnaserror+",
        "-target:exe", f"-main:{main}", f"-out:{output}",
        *(f"-reference:{path}" for path in [*references, *(extra_references or [])]),
        *(str(path) for path in sources),
    ]


def _native_validate(
    root: Path, project: dict[str, Any], dotnet: Path, sdk_root: Path,
) -> tuple[dict[str, Any], dict[str, Any] | None]:
    compiler = sdk_root / "Roslyn/bincore/csc.dll"
    try:
        references, code_analysis, csharp_analysis, runtime_version = _sdk_assets(dotnet, sdk_root)
    except ValueError as exc:
        return {"state": "sdk-assets-unavailable", "detail": str(exc)}, None
    build = root / ".native-build"
    build.mkdir(parents=True, exist_ok=True)
    sources = [root / relative for relative in project["sources"]]
    tests = [root / relative for relative in project["tests"]]
    app = build / "csharp-app.dll"
    test_app = build / "csharp-tests.dll"
    commands = {
        "compile": _compile_command(dotnet, compiler, references, app, sources, project["smoke_main"]),
        "compile-tests": _compile_command(
            dotnet, compiler, references, test_app, [*sources, *tests], project["test_main"]
        ),
        "smoke": [str(dotnet), str(app)],
        "test": [str(dotnet), str(test_app)],
    }
    compile_results: dict[str, subprocess.CompletedProcess[str]] = {}
    for name in ("compile", "compile-tests"):
        compile_results[name] = _run(commands[name], root, timeout=180)
        if compile_results[name].returncode:
            return {
                "state": "compiler-diagnostic-failed", "failed_command": name,
                "returncode": compile_results[name].returncode,
                "stdout": compile_results[name].stdout[:2000],
                "stderr": compile_results[name].stderr[:5000], "commands": commands,
            }, None
    _runtime_config(build / "csharp-app.runtimeconfig.json", runtime_version)
    _runtime_config(build / "csharp-tests.runtimeconfig.json", runtime_version)
    checks = {name: _run(commands[name], root, timeout=60) for name in ("test", "smoke")}
    if (
        any(result.returncode for result in checks.values())
        or checks["test"].stdout != project["test_output"]
        or checks["smoke"].stdout != project["smoke_output"]
    ):
        return {
            "state": "native-replay-failed", "commands": commands,
            "checks": {name: {
                "returncode": result.returncode, "stdout": result.stdout, "stderr": result.stderr,
            } for name, result in checks.items()},
        }, None
    return {
        "state": "valid-current-and-replayed", "commands": commands,
        "test_stdout": checks["test"].stdout, "smoke_stdout": checks["smoke"].stdout,
        "runtime_version": runtime_version,
    }, {
        "compiler": compiler, "references": references,
        "code_analysis": code_analysis, "csharp_analysis": csharp_analysis,
        "runtime_version": runtime_version,
    }


def _syntax_files(
    root: Path, sources: list[Path], dotnet: Path, assets: dict[str, Any],
) -> tuple[list[dict[str, Any]], str | None]:
    helper_source = Path(__file__).with_name("CSharpSyntaxFacts.cs")
    with tempfile.TemporaryDirectory(prefix="csharp-facts-") as raw_temporary:
        temporary = Path(raw_temporary)
        helper = temporary / "CSharpSyntaxFacts.dll"
        command = _compile_command(
            dotnet, assets["compiler"], assets["references"], helper, [helper_source],
            "CSharpSyntaxFacts", [assets["code_analysis"], assets["csharp_analysis"]],
        )
        compiled = _run(command, root, timeout=180)
        if compiled.returncode:
            return [], f"helper compile failed: {compiled.stderr[:4000]}"
        shutil.copy2(assets["code_analysis"], temporary / assets["code_analysis"].name)
        shutil.copy2(assets["csharp_analysis"], temporary / assets["csharp_analysis"].name)
        _runtime_config(temporary / "CSharpSyntaxFacts.runtimeconfig.json", assets["runtime_version"])
        analyzed = _run([str(dotnet), str(helper), *(str(path) for path in sources)], root, timeout=120)
        if analyzed.returncode:
            return [], f"helper execution failed: {analyzed.stderr[:4000]}"
        try:
            rows = json.loads(analyzed.stdout)["files"]
        except (json.JSONDecodeError, KeyError, TypeError) as exc:
            return [], f"helper output invalid: {exc}"
    results: list[dict[str, Any]] = []
    for row in rows:
        path = Path(row["path"])
        relative = path.relative_to(root).as_posix()
        digest = hash_bytes(path.read_bytes())
        for token in row["identifier_tokens"]:
            token["span"] = {"start_byte": token["span"]["start"], "end_byte": token["span"]["end"]}
        for comment in row["comments"]:
            comment["span"] = {"start_byte": comment["span"]["start"], "end_byte": comment["span"]["end"]}
        functions: list[dict[str, Any]] = []
        for function in row["functions"]:
            function.pop("body")
            normalized = function.pop("normalized_body")
            spelling = function.pop("spelling")
            function["source_sha256"] = digest
            function["file"] = relative
            function["spelling_sha256"] = hash_bytes(spelling.encode())
            function["normalized_body_sha256"] = hash_bytes(normalized.encode())
            for call in function["calls"]:
                call["span"] = {"start_byte": call["span"]["start"], "end_byte": call["span"]["end"]}
                call["claim"] = "unresolved-direct-call-spelling"
            functions.append(function)
        results.append({
            "file": relative, "namespace": row["namespace"], "usings": row["usings"],
            "source_sha256": digest, "comments": row["comments"],
            "identifier_tokens": row["identifier_tokens"],
            "declarations": row["declarations"], "functions": functions,
            "diagnostics": row["diagnostics"],
        })
    return results, None


def _base_payload(
    root: Path, target: Path, inventory: list[dict[str, Any]], before: dict[str, str],
    tools: dict[str, Any], project: dict[str, Any] | None,
) -> dict[str, Any]:
    return {
        "schema_version": 1, "status": "failed", "failure_kind": "unknown",
        "language": "csharp", "syntax_standard": "C# 14 / .NET 10 source syntax",
        "analyzer": "dotnet-sdk-10.0.302-roslyn-syntax",
        "project_root": str(root), "target": str(target), "tools": tools,
        "project_manifest": project, "inventory": inventory, "files": [],
        "native_evidence": {"state": "not-validated"},
        "source_manifest": {
            "before": before, "before_sha256": _manifest_hash(before),
            "after": None, "after_sha256": None, "preserved": False,
        },
        "boundaries": {
            "eligible_sources": "exact lowercase .cs paths declared by csharp-project.json",
            "source_roles": "test, generated, vendor, build, tooling, unreadable, and symlink paths excluded",
            "resolved_symbols": "not available", "resolved_calls": "not available",
            "overrides": "not analyzed", "data_flow": "not analyzed",
            "compiler_ir": "not consumed", "runtime_behavior": "not proven",
        },
        "limits": [
            "Roslyn syntax nodes, tokens, comments, declarations, branch constructs, and direct call spellings are source syntax only.",
            "No resolved symbols, call targets, overload binding, overrides, data flow, reflection, compiler IR, or runtime behavior are claimed.",
            "Only exact lowercase .cs C# 14 inputs in csharp-project.json are eligible; generated code, analyzers, source generators, MSBuild evaluation, and multi-targeting are outside scope.",
        ],
    }


def _finish(payload: dict[str, Any], root: Path, before: dict[str, str]) -> tuple[dict[str, Any], int]:
    after_inventory, after = _inventory(root)
    payload["inventory"] = after_inventory
    payload["source_manifest"].update(
        after=after, after_sha256=_manifest_hash(after), preserved=before == after,
    )
    if before != after:
        payload.update(status="failed", failure_kind="unexpected_source_mutation", files=[])
        return payload, 2
    return payload, terminal_return_code(payload)


def produce(
    project_root: Path, target: Path, *, dotnet: str | None,
) -> tuple[dict[str, Any], int]:
    try:
        root = project_root.resolve(strict=True)
    except (OSError, RuntimeError):
        root = project_root.resolve()
        return {
            "status": "failed", "failure_kind": "project_root_invalid",
            "language": "csharp", "project_root": str(root), "files": [],
        }, 2
    requested_target = target if target.is_absolute() else root / target
    try:
        selected_target = requested_target.resolve(strict=True)
    except (OSError, RuntimeError):
        selected_target = requested_target.resolve()
    inventory, before = _inventory(root)
    dotnet_probe, dotnet_path, sdk_root = _probe_dotnet(root, dotnet)
    payload = _base_payload(root, selected_target, inventory, before, {"dotnet": dotnet_probe}, None)
    if not root.is_dir() or root.is_symlink() or not _inside(selected_target, root):
        payload.update(failure_kind="project_or_target_invalid")
        return _finish(payload, root, before)
    if dotnet_path is None or sdk_root is None:
        state = dotnet_probe["status"].replace("-", "_")
        payload.update(status="unsupported", failure_kind=f"dotnet_tool_{state}")
        return _finish(payload, root, before)
    try:
        project = _load_project(root, inventory)
    except ValueError as exc:
        payload.update(failure_kind="csharp_project_manifest_invalid", detail=str(exc))
        return _finish(payload, root, before)
    payload["project_manifest"] = project
    evidence, assets = _native_validate(root, project, dotnet_path, sdk_root)
    payload["native_evidence"] = evidence
    if assets is None:
        failure = "csharp_compiler_diagnostic_failed" if evidence["state"] == "compiler-diagnostic-failed" else f"csharp_{evidence['state'].replace('-', '_')}"
        payload.update(failure_kind=failure)
        return _finish(payload, root, before)
    selected_sources = [
        root / relative for relative in project["sources"]
        if _inside(root / relative, selected_target)
        or (selected_target.is_file() and root / relative == selected_target)
    ]
    files, error = _syntax_files(root, selected_sources, dotnet_path, assets)
    if error:
        payload.update(failure_kind="csharp_roslyn_syntax_failed", detail=error)
    else:
        payload.update(status="complete", failure_kind="none", files=files)
    return _finish(payload, root, before)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, type=Path)
    parser.add_argument("--target", required=True, type=Path)
    parser.add_argument("--json", action="store_true")
    add_fact_arguments(parser)
    return parser


def main(argv: Iterable[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    payload, code = produce(args.project_root, args.target, dotnet=args.dotnet)
    print(json.dumps(payload, indent=2, sort_keys=True))
    return code


if __name__ == "__main__":
    raise SystemExit(main())
